### ISSUE TITLE
no support for kali 2.0

### ISSUE THREAD

**Issue by Darkcast** [entropy1337/infernal-twin#4]
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'console'
  warnings.warn(msg)

**Comment by entropy1337** [comment]
hello Darkcast, 
could you please share the screenshot or more details. I will try to correct it. 
thank you for your feedback.

**Comment by lightos** [comment]
I commented out the following for it to run in Kali 2.0:
./notepad.py:3:from wxPython.wx import *
./wpa2_hack.py:3:from wxPython.wx import *
./fakePagecreate.py:3:from wxPython.wx import *

**Comment by entropy1337** [comment]
Hello there,
Did that fix the issue ?
If so thank you for this comment.
I did not really tested it out on kali 2.

**Comment by entropy1337** [comment]
I also would suggest you to download latest version as I made small
changes. Thanks

**Comment by lightos** [comment]
Well you are already importing wx, so doing "from wxPython.wx import *" on top of that seems redundant and at least in Kali 2.0 causes an error because the library can't be found.

To get it working on Kali 2.0 out of the box I just commented out "from wxPython.wx import *" from the 3 files previously mentioned and the program ran.

I will give the new version a try, thanks!

**Comment by entropy1337** [comment]
thank you lightos, 
i did put the try and catch block and it is working under kali 2

**Comment by rajunromen** [comment]
@entropy1337. Can I run it using Phyton 3.5 on Windows?

**Comment by entropy1337** [comment]
Unfortunately you can't run this tool under Windows.
