### ISSUE TITLE
Two Wifi cards

### ISSUE THREAD

**Issue by jhussni** [entropy1337/infernal-twin#41]
Hey,

How are u? Very very nice work in this project!

I am making some hard test here, and expect give you some feedback.

I have a question for now, i have two cards, one is pci of laptop another is a TP-Link / Bus 001 Device 019: ID 0cf3:9271 Atheros Communications, Inc. AR9271 802.11n

I have also a 25dbi 2.4 ghz antenna booster connect at it, but the Infernal dont start a scan in my usb wifi card?

Some tip to help me guys?

Reggards!

**Comment by entropy1337** [comment]
Hello Jhussni,
I would love more feedbacks.
Please share the result of your iwconfig output. I don't know why it is
happening. I will try to replicate it.

**Comment by zstyblik** [comment]
I believe this comes from the fact there is no way to specify which interface is going to be used for what right now.

**Comment by entropy1337** [comment]
Hello Jhussni, 
I have recently put a feature for the user to specify which outbound interface card to use for evil twin or MITM attacks. so, you have one card broadcasting fake AP and you can choose from dropdown menu what card to use to redirect the net traffic to. Please have a look at the sample if you prefer more things, please specify so that we could work on. 
![sample](https://cloud.githubusercontent.com/assets/10882843/12402071/104820c0-be44-11e5-8f91-79cab693a4be.png)

**Comment by entropy1337** [comment]
you can specify your second wifi card from drop down menu. This option is only enabled for Evil Twin attack. Would you prefer this option for other MiTM or other attacks in a similar manner ?

**Comment by entropy1337** [comment]
it is implemented now.
